var places = [
  {
    name: 'Schwack Beach Grill',
    address: '24502 Del Prado Ave Dana Point, CA 92629',
    range: 1,
    hours: 'Mon-Sun 8:00am - 9:00pm',
    delivery: 'Yes',
    reservations: 'No',
    creditCard: 'Yes',
    wifi: 'Yes',
    goodFor: 'Lunch',
    alcohol: 'Beer and Wine Only'
  },
  {
    name: 'Two Left Forks',
    address: '34212 Pacific Coast Hwy Dana Point, CA 92629',
    range: 2,
    hours: 'Tue-Sun 4:00pm - 11:00pm',
    delivery: 'No',
    reservations: 'Yes',
    creditCard: 'Yes',
    wifi: 'Yes',
    goodFor: 'Dinner',
    alcohol: 'Full Bar'
  },
  {
    name: 'The Point',
    address: '34085 Pacific Coast Hwy Dana Point, CA 92629',
    range: 2,
    hours: 'Mon-Sun 11:30am - 2:00am',
    delivery: 'No',
    reservations: 'Yes',
    creditCard: 'Yes',
    wifi: 'No',
    goodFor: 'Dinner',
    alcohol: 'Full Bar'
  },
  {
    name: 'Coastal Kitchen',
    address: '4091 Pacific Coast Hwy Dana Point, CA 92629',
    range: 3,
    hours: 'Mon-Sun 11:30am - 9:30pm',
    delivery: 'No',
    reservations: 'Yes',
    creditCard: 'Yes',
    wifi: 'No',
    goodFor: 'Dinner',
    alcohol: 'Full Bar'
  },
  {
    name: 'Stacks Pancake House',
    address: '34255 Pacific Coast Hwy Ste 110 Dana Point, CA 92629',
    range: 1,
    hours: 'Mon-Sun 11:30am - 9:30pm',
    delivery: 'No',
    reservations: 'No',
    creditCard: 'Yes',
    wifi: 'No',
    goodFor: 'Breakfast',
    alcohol: 'No'
  },
  {
    name: 'Jack’s Restaurant',
    address: '24462 Del Prado  Dana Point, CA 92629',
    range: 2,
    hours: 'Mon-Sun 5:00pm - 9:30pm',
    delivery: 'No',
    reservations: 'Yes',
    creditCard: 'Yes',
    wifi: 'No',
    goodFor: 'Dinner',
    alcohol: 'Full Bar'
  },
  {
  name: 'Taco Surf',
  address: '34195 Pacific Coast Hwy Dana Point, CA 92629',
  range: 1,
  hours: 'Mon-Sun 11:am - 9:00pm',
  delivery: 'No',
  reservations: 'No',
  creditCard: 'Yes',
  wifi: 'No',
  goodFor: 'Dinner',
  alcohol: 'Full Bar'
  },
  {
  name: 'Harbor House Cafe',
  address: '34157 Pacific Coast Hwy Dana Point, CA 92629',
  range: 1,
  hours: 'Mon-Sun Open 24 Hours',
  delivery: 'No',
  reservations: 'No',
  creditCard: 'Yes',
  wifi: 'No',
  goodFor: 'Breakfast',
  alcohol: 'No'
  },
  {
  name: 'Tutor & Spunky’s Deli',
  address: '34085 Pacific Coast Hwy Ste 116-117 Dana Point, CA 92629',
  range: 1,
  hours: 'Mon-Sun 7:00am - 7:00pm',
  delivery: 'Yes',
  reservations: 'No',
  creditCard: 'No',
  wifi: 'Yes',
  goodFor: 'Lunch',
  alcohol: 'No'
  },
];
